name: Setup Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_NOTIFY_DAPP_ID: ${{ secrets.REACT_APP_NOTIFY_DAPP_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  setup:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REACT_APP_NOTIFY_DAPP_ID: ${{ secrets.REACT_APP_NOTIFY_DAPP_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
